### ISSUE TITLE
Can't scroll Deck up and down.

### ISSUE THREAD

**Issue by polocatfan** [eyal282/chrome-ext-dueling-book-unlock#1]
EDIT: Forgot to mention the chrome store version works fine, but the master build is having the issue.
EDIT 2: Chrome Store version is now having the same issue.

**Comment by eyal282** [comment]
> EDIT: Forgot to mention the chrome store version works fine, but the master build is having the issue. EDIT 2: Chrome Store version is now having the same issue.

This is fixed as of next version. Can you try again?

**Comment by polocatfan** [comment]
Master Build seems to be outdated and still has the issue, but the Chrome Store version is working now.

**Comment by eyal282** [comment]
> Master Build seems to be outdated and still has the issue, but the Chrome Store version is working now.

I'll update it today. Forgot about it.
